### ISSUE TITLE
pom.xml in git lfs

### ISSUE THREAD

**Issue by LeonBein** [eclab/mason#21]
Hi, the pom files are still included in git lfs:
![grafik](https://user-images.githubusercontent.com/28008098/83397004-36d1e480-a3fd-11ea-861b-eb38484c34c5.png)
As commit 18319a3aaa7ceadacdd06ef11fa95570c8eb6275 states that this should not be the case anymore, I assume this is a bug.

**Comment by rajdeepslather** [comment]
Thanks for pointing it out, we'll look into it.

**Comment by LeonBein** [comment]
Seems to have been fixed in 5e541990bf871680ed9c8da20c67608873fabd1f?
