### ISSUE TITLE
ECJ dependency breaks Maven build

### ISSUE THREAD

**Issue by SigmaX** [eclab/mason#32]
A colleague pointed out to me that `mvn install` fails right now because the `serengeti` and `opt` packages are part of the main source tree, but they depend on ECJ.

Since ECJ releases are not registered with the Maven central repo, the dependency cannot be handled automatically.

I can think of four solutions:

1. Add a Maven profile that omits these packages from the standard build, allowing them to be built with a flag
2. Require all users to install ECJ manually to their classpath or local Maven repo before building Mason (but bleh, I hate complicated build procedures)
3. Publish ECJ in Maven Central
4. Remove `serengeti` and `opt` to a `contrib` package.

It looks like @rmoffatt might already be doing (4).  If it's already moved, can we delete the problem packages from the `mason/src` tree?

**Comment by eclab** [comment]
Deleted.  They are already in contrib.

Sean

**Comment by SigmaX** [comment]
Thanks!  Builds fine now.
