### ISSUE TITLE
undesired (?) println in ShapeFileImporter.java (Geomason)

### ISSUE THREAD

**Issue by g-filomena** [eclab/mason#53]
The function `private static Geometry createPolygon(final LinearRing[] parts)` in /geomason/src/main/java/sim/io/geo/ShapeFileImporter.java contains the row `System.out.println("createPolygon");`  that prompts an undesired amount of output lines when importing a shapefile containing polygons.

I wonder if this is meant to happen or rather something that was forgotten there following the development phase.

**Comment by eclab** [comment]
It's clearly part of development: I deleted it.
