### ISSUE TITLE
Description and RemoteProxy showing up uninvited in the Model tab

### ISSUE THREAD

**Issue by jharrison** [eclab/mason#54]
There are two items showing up in the model tab that weren't there before. You can see them in this picture of the HeatBugs GUI, 4th from the top and last. I checked and they're in Flockers too.

![image](https://user-images.githubusercontent.com/251553/112215711-10cd3900-8bf7-11eb-8d31-a5710b9860ca.png)

**Comment by eclab** [comment]
Fixed.  One was a property introduced for optimization and one was introduced for distributed MASON, sorry.

Sean

**Comment by jharrison** [comment]
Thanks!
