### ISSUE TITLE
Not compiling with jdk11 LTS

### ISSUE THREAD

**Issue by alonsoir** [eclab/mason#59]
[INFO] 4 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Logistic.java:[12,31] cannot find symbol
  symbol: class AbstractContinousDistribution
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Empirical.java:[36,32] cannot find symbol
  symbol: class AbstractContinousDistribution
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Logistic.java:[16,9] cannot find symbol
  symbol:   method setRandomGenerator(ec.util.MersenneTwisterFast)
  location: class sim.util.distribution.Logistic
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Logistic.java:[21,43] cannot find symbol
  symbol:   variable randomGenerator
  location: class sim.util.distribution.Logistic
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Logistic.java:[26,20] cannot find symbol
  symbol: method getClass()
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Empirical.java:[59,9] cannot find symbol
  symbol:   method setRandomGenerator(ec.util.MersenneTwisterFast)
  location: class sim.util.distribution.Empirical
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Empirical.java:[87,23] cannot find symbol
  symbol:   variable randomGenerator
  location: class sim.util.distribution.Empirical
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Empirical.java:[185,20] cannot find symbol
  symbol: method getClass()
[INFO] 8 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for mason 20:
[INFO] 
[INFO] mason .............................................. SUCCESS [  0.808 s]
[INFO] mason .............................................. FAILURE [  9.254 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.128 s
[INFO] Finished at: 2022-03-20T15:12:26+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project mason: Compilation failure: Compilation failure: 
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Logistic.java:[12,31] cannot find symbol
[ERROR]   symbol: class AbstractContinousDistribution
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Empirical.java:[36,32] cannot find symbol
[ERROR]   symbol: class AbstractContinousDistribution
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Logistic.java:[16,9] cannot find symbol
[ERROR]   symbol:   method setRandomGenerator(ec.util.MersenneTwisterFast)
[ERROR]   location: class sim.util.distribution.Logistic
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Logistic.java:[21,43] cannot find symbol
[ERROR]   symbol:   variable randomGenerator
[ERROR]   location: class sim.util.distribution.Logistic
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Logistic.java:[26,20] cannot find symbol
[ERROR]   symbol: method getClass()
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Empirical.java:[59,9] cannot find symbol
[ERROR]   symbol:   method setRandomGenerator(ec.util.MersenneTwisterFast)
[ERROR]   location: class sim.util.distribution.Empirical
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Empirical.java:[87,23] cannot find symbol
[ERROR]   symbol:   variable randomGenerator
[ERROR]   location: class sim.util.distribution.Empirical
[ERROR] /Users/aironman/git/mason/mason/src/main/java/sim/util/distribution/Empirical.java:[185,20] cannot find symbol
[ERROR]   symbol: method getClass()
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :mason
[dom 22/03/20 15:12 CET][s000][x86_64/darwin21.0/21.3.0][5.8]
<aironman@MacBook-Pro-de-Alonso:~/git/mason>
zsh 4880 [1] master% mvn --version    
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /Users/aironman/.sdkman/candidates/maven/current
Java version: 11.0.14.1, vendor: Amazon.com Inc., runtime: /Users/aironman/.sdkman/candidates/java/11.0.14.10.1-amzn
Default locale: es_ES, platform encoding: UTF-8
OS name: "mac os x", version: "12.2.1", arch: "x86_64", family: "mac"
[dom 22/03/20 15:13 CET][s000][x86_64/darwin21.0/21.3.0][5.8]
<aironman@MacBook-Pro-de-Alonso:~/git/mason>
zsh 4881 master%

**Comment by eclab** [comment]
This appears to simply be an issue where Maven's build file hasn't been updated yet: all of the classes are there and it compiles clean with make or, heck, with javac.  Unfortunately we can't update maven right now, someone else will have to handle it.

**Comment by alonsoir** [comment]
I think that you have a jar with source files added to your classpath and you don't upload it. Nobody can handle it unless you provide those .java files.

**Comment by rajicon** [comment]
The issue should be fixed now, I pushed the changes.
