### ISSUE TITLE
How do I use MASON with maven?

### ISSUE THREAD

**Issue by jharrison** [eclab/mason#9]
Is there a working maven build file?

**Comment by hatFolk** [comment]
It's a work in progress.

You can see some of our attempts in other branches that are named Maved, Fresh_Mavenization, Mavenized, etc.

We'll merge these soon-- as soon we can establish stability

**Comment by usuallycwdillon** [comment]
In the mean time, you can import MASON into your local Maven repository (mine came up as `edu.gmu.eclab:mason:19` and use a standard dependency entry in your pom file. 
```
<dependency>
      <groupId>edu.gmu.eclab</groupId>
      <artifactId>mason</artifactId>
      <version>19</version>
    </dependency>
```

**Comment by rajdeepslather** [comment]
MASON has been Mavenized so now you should be able to use 'Maven install' to build it.

**Comment by ruloweb** [comment]
I think that the issue was that it is not possible to install MASON using maven. Looks like the last version in the [mvn repository](https://mvnrepository.com/artifact/edu.gmu.cs/mason) is 14.0.

Are you folks planning to publish MASON into maven again?

Thanks!
